Below is a function that has an input of a 2x2 matrix, and an output of the transition matrix P and the Jordan form J.

This is done without using preexisting Jordan Form libraries to show the python code directly.

In [3]:

import scipy as sc
from itertools import chain
import sympy as sp
import numpy as np

def jordan(matrix):
    m = sp.Matrix(matrix)
    diag = m.is_diagonalizable()
    if(diag):
      eigs = sorted(m.eigenvects(), key=lambda x:x[0])
      eigs.reverse()
      P=[]
      P.append(list(chain.from_iterable(eigs[0][2])))
      P.append(list(chain.from_iterable(eigs[1][2])))
      P = [[P[0][0], P[1][0]],[P[0][1], P[1][1]]]
      #for tup in eigs:
      #  for v in tup[2]:
      #    P.append(list(v))
      J = [[0, 0], [0, 0]]
      eigvs = m.eigenvals()
      
      J[0][0] = list(eigvs.items())[0][0]
      J[1][1] = list(eigvs.items())[1][0]
          
    else:
      P=[]
      eigvs = m.eigenvals()
      J = [[list(eigvs.items())[0][0],1],[0,list(eigvs.items())[0][0]]]
      
      eigs = m.eigenvects()


      n = list(eigvs.items())[0][0] * sp.Matrix(np.eye(2))
      x = (m - n) ** 2

      nullspace = sc.linalg.null_space(np.array(x).astype(int))
      
      P=[]
      for tup in eigs:
        for v in tup[2]:
          P.append(list(v))
      n = list(eigvs.items())[0][0] * sp.Matrix(np.eye(2))
      m = (m - n) ** 2
      eigs = m.eigenvects()
      found = 0
      
      for tup in eigs:
        for v in tup[2]:
          if found:
            break
          if (list(v) not in nullspace):
            P.append(list(v))
            found = 1
      if found != 1:

        for tup in eigs:
          for v in tup[2]:
            x = list(v)
            P = [[P[0][0], x[0]], [P[0][1], x[1]]]
            P = np.array(P).astype(int)
            if not np.array_equal(np.matmul(np.matmul(P, J), np.linalg.inv(P)).astype(int), np.array(matrix).astype(int)):
              x[0] = x[0] * -1 
              P = [[P[0][0], x[0]], [P[0][1], x[1]]]

            break
    
    P = np.array(P).astype(int)
    J = np.array(J).astype(int) 

    return P, J


Testing the function below. 

In [ ]:
A = [[1, 1], [1, 1]]
jordan(A)

(array([[ 1, -1],
        [ 1,  1]]),
 array([[2, 0],
        [0, 0]]))

In [ ]:
A = [[1, 1], [-1, -1]]
jordan(A)

(array([[-1, -1],
        [ 1,  0]]),
 array([[0, 1],
        [0, 0]]))

In [ ]:
A  = [[4, 1], [-1, 2]]
jordan(A)

(array([[-1, -1],
        [ 1,  0]]),
 array([[3, 1],
        [0, 3]]))